inherit_from: .rubocop_todo.yml
require: rubocop-rails
AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'

Rails/LexicallyScopedActionFilter:
  Enabled: false
